kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-mathew
subjects:
- kind: ServiceAccount
  name: operator-mathew
roleRef:
  kind: Role
  name: operator-mathew
  apiGroup: rbac.authorization.k8s.io
